### ISSUE TITLE
Type annotations?

### ISSUE THREAD

**Issue by jamesob** [buidl-bitcoin/buidl-python#136]
What's the thinking around adding type annotations? I think in certain cases it could be very helpful, but don't want to start down that road if that's out of alignment with the goals of the project.

**Comment by jimmysong** [comment]
It could be useful, but honestly, I don't want to turn this into a strongly typed library.

**Comment by jimmysong** [comment]
I can see the argument for it, but I'd rather document things more naturally through explicit documentation or implicit in the function/method names. Appreciate the advocacy, though!

**Comment by jimmysong** [comment]
It's open source for that reason! Please feel free to fork!

**Comment by mflaxman** [comment]
@jamesob can you explain a little more why you like the annotations? I don't like them in general because they've always felt unpythonic to me: they're hard to read, not strictly enforced, and you don't get the performance benefits other languages get with strong typing.

It's not a knock on strong typing, it has tradeoffs that are often good for bitcoin apps. In some ways I feel more comfortable using golang with bitcoin for example.

I appreciate the signet PR so I don't want to be turning you off of buidl unnecessarily! I'd like to understand your perspective better.

**Comment by jamesob** [comment]
> they're hard to read

Matter of personal preference I guess, but I find them really readable - I like having an unambiguous place to look that tells me the return type of a function, or what the expected type of a parameter is. Code winds up being much easier for me to explore and use that way.

> not strictly enforced

Now that there's pretty decent third-party tooling, annotations can actually be checked in the development and linting phase. E.g., using [pyright](https://github.com/microsoft/pyright):

![image](https://user-images.githubusercontent.com/73197/156624343-95aa4e0a-f46c-4d8f-9648-0db44b003f4f.png)

In my project [coldcore](https://github.com/jamesob/coldcore) (a kindred spirit to this library) for example, one of the CI steps is running mypy to check the annotations for correctness.
